import React from "react";
import Print from "../../../common/print/Print";
import { Link } from "react-router-dom";
import { MdOutlineLocalHospital } from "react-icons/md";
function PathologyBillDetails() {
  return (
    <div className="patient_profile_main_sec">
      <div className="prescription_header_sec">
        <div>
          <h4>Pathology Bill Details</h4>
        </div>
        <div>
          <div className="d-flex" style={{ alignItems: "center" }}>
            <div className="mr-2">
              <Print />
            </div>
            <Link to="/admin/PathologyBill-List" className="back_btn">
              Back
            </Link>
          </div>
        </div>
      </div>
      <div className="prescription_body_sec">
        <div className="modal-body pt0 pb0">
          <div className="row">
            <div className>
              <div className="d-flex">
                <div className="">
                  <table className="table table-hover table-sm">
                    <tbody>
                      <tr>
                        <td className="col-lg-3">
                          <label>Bill No</label>
                        </td>
                        <td className="col-lg-3">PATHOB441</td>
                      </tr>
                      <tr>
                        <td className="col-lg-3">
                          <label>Prescription No</label>
                        </td>
                        <td className="col-lg-3">IPDP294</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Doctor Name</label>
                        </td>
                        <td>Sansa Gomez (9008)</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Blood Group</label>
                        </td>
                        <td>AB-</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Generated By</label>
                        </td>
                        <td>Super Admin (9001)</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Note</label>
                        </td>
                        <td />
                      </tr>
                      <tr>
                        <td>
                          <label>Previous Report Value</label>
                        </td>
                        <td />
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div className="">
                  <table className="table table-hover table-sm">
                    <tbody>
                      <tr>
                        <td className="col-lg-3">
                          <label>Case ID</label>
                        </td>
                        <td className="col-lg-3">6290</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Age</label>
                        </td>
                        <td>25 Year 20 Days </td>
                      </tr>
                      <tr>
                        <td>
                          <label>Mobile No</label>
                        </td>
                        <td>94564651414</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Address</label>
                        </td>
                        <td>CA.West </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div className="">
                  <table className="table table-hover table-sm">
                    <tbody>
                      <tr>
                        <td>
                          <label>Patient Name</label>
                        </td>
                        <td>Nishant Kadakia (980)</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Gender</label>
                        </td>
                        <td>Male</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Email</label>
                        </td>
                        <td>Nishant25@gmail.com</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div className="">
                  <table className="table table-hover table-sm">
                    <tbody>
                      <tr>
                        <td>
                          <label>Total</label>
                        </td>
                        <td className="col-lg-3 text text-right">$150.00</td>
                      </tr>
                      <tr>
                        <td className="col-lg-3">
                          <label>Total Discount</label>
                        </td>
                        <td className="col-lg-3 text text-right">
                          (0.00%) $0.00
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <label>Total Tax</label>
                        </td>
                        <td className="col-lg-3 text text-right">$45.00</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Net Amount</label>
                        </td>
                        <td className="col-lg-3 text text-right">$195.00</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Total Deposit</label>
                        </td>
                        <td className="col-lg-3 text text-right">$150.00</td>
                      </tr>
                      <tr>
                        <td>
                          <label>Balance Amount</label>
                        </td>
                        <td className="col-lg-3 text text-right">$45.00</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              {/* //============= */}
              <div className="table-responsive">
                <div className="col-md-12">
                  <table className="table table-hover table-sm">
                    <thead>
                      <tr className="line">
                        <td>
                          <strong>#</strong>
                        </td>
                        <td>
                          <strong>Test Name</strong>
                        </td>
                        <td width="25%">
                          <strong>Sample Collected</strong>
                        </td>
                        <td>
                          <strong>Expected Date</strong>
                        </td>
                        <td>
                          <strong>Approved By</strong>
                        </td>
                        <td className="text-right">
                          <strong>Tax</strong>
                        </td>
                        <td className="text-right">
                          <strong>Amount</strong>
                        </td>
                        <td className="text-right">
                          <strong>Action</strong>
                        </td>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>
                          <strong>Abdomen X-rays</strong>
                          <br />
                          (AX){" "}
                        </td>
                        <td className="text-left">
                          <label>Belina Turner (9005) </label>
                          <br />
                          <label htmlFor>Pathology: </label>
                          In-House Pathology Lab <br />
                          06/22/2024
                        </td>
                        <td>06/23/2024</td>
                        <td className="text-left">
                          <label htmlFor>Approved By : </label>
                          Reyan Jain (9011) <br />
                          06/24/2024
                        </td>
                        <td className="text-right">$45.00(30.00%)</td>
                        <td className="text-right">$150.00</td>
                        <td className="text-right">
                          <a
                            href="javascript:void(0)"
                            data-loading-text='<i class="fa fa-circle-o-notch fa-spin"></i>'
                            data-record-id={719}
                            className="btn btn-default btn-xs print_pathology_report"
                            data-toggle="tooltip"
                            title="Print"
                          >
                            <i className="fa fa-print" />
                          </a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* <MadicineDetailsTab /> */}
      </div>
    </div>
  );
}

export default PathologyBillDetails;
