import React from "react";
import Print from "../../../common/print/Print";
import { Link } from "react-router-dom";

function RadiologyBillDetails() {
  return (
    <div className="patient_profile_main_sec">
      <div className="prescription_header_sec">
        <div>
          <h4>Radiology Bill Details</h4>
        </div>
        <div>
          <div className="d-flex" style={{ alignItems: "center" }}>
            <div className="mr-2">
              <Print />
            </div>
            <Link to="/admin/Radiology" className="back_btn">
              Back
            </Link>
          </div>
        </div>
      </div>
      <div className="prescription_body_sec">
        <div className="modal-body pt0 pb0">
          <div className="row">
            <div className="table-responsive">
              <div className="">
                <table className="table ">
                  <tbody>
                    <tr>
                      <th>
                        <label>Bill No</label>
                      </th>
                      <td>RADIOB381</td>
                      <th>
                        <label>Case ID</label>
                      </th>
                      <td>6290</td>
                      <th>
                        <label>Prescription No</label>
                      </th>
                      <td>IPDP294</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Generated By</label>
                      </th>
                      <td>Super Admin (9001)</td>
                      <th>
                        <label>Age</label>
                      </th>
                      <td>25 Year 20 Days</td>
                      <th>
                        <label>Patient Name</label>
                      </th>
                      <td>Nishant Kadakia (980)</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Blood Group</label>
                      </th>
                      <td>AB-</td>
                      <th>
                        <label>Mobile No</label>
                      </th>
                      <td>94564651414</td>
                      <th>
                        <label>Gender</label>
                      </th>
                      <td>Male</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Doctor Name</label>
                      </th>
                      <td>Sonia Bush (9002)</td>
                      <th>
                        <label>Address</label>
                      </th>
                      <td>CA.West </td>
                      <th>
                        <label>Email</label>
                      </th>
                      <td>Nishant25@gmail.com</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Previous Report Value</label>
                      </th>
                      <td className="text text-right" />
                      <th />
                      <td />
                      <th />
                      <td />
                    </tr>
                    <tr>
                      <th />
                      <td />
                      <th />
                      <td />
                      <th />
                      <td />
                    </tr>
                  </tbody>
                </table>
              </div>
              <div className="">
                <table className="table ">
                  <tbody>
                    <tr>
                      <th>
                        <label>Total</label>
                      </th>
                      <td className="text text-right">$160.00</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Discount</label>
                      </th>
                      <td className="text text-right">$0.00</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Tax</label>
                      </th>
                      <td className="text text-right">$32.00</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Net Amount</label>
                      </th>
                      <td className="text text-right">$192.00</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Total Deposit</label>
                      </th>
                      <td className="text text-right">$120.00</td>
                    </tr>
                    <tr>
                      <th>
                        <label>Due Amount</label>
                      </th>
                      <td className="text-right">$72.00</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="">
              <div className="">
                <table className="table ">
                  <thead>
                    <tr className="line">
                      <td>
                        <strong>#</strong>
                      </td>
                      <td className="text-left">
                        <strong>Test Name</strong>
                      </td>
                      <td className="text-left">
                        <strong>Sample Collected</strong>
                      </td>
                      <td className="text-center">
                        <strong>Expected Date</strong>
                      </td>
                      <td className="text-left">
                        <strong>Approved By / Update Date</strong>
                      </td>
                      <td className="text-right">
                        <strong>Tax</strong>
                      </td>
                      <td className="text-right">
                        <strong>Amount</strong>
                      </td>
                      <td className="text-right">
                        <strong>Action</strong>
                      </td>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>
                        <strong>Functional MRI (RI)</strong>
                        <br />
                        (FMRI)
                      </td>
                      <td className="text-left">
                        <label>John Hook (9006) </label>
                        <br />
                        <label htmlFor>Radiology : </label>In-House Radiology
                        Lab
                        <br />
                        06/21/2024
                      </td>
                      <td className="text-center">06/22/2024</td>
                      <td className="text-left">
                        <label htmlFor>Approved By : </label>Reyan Jain (9011){" "}
                        <br />
                        06/23/2024{" "}
                      </td>
                      <td className="text-right">$32.00 (20.00%) </td>
                      <td className="text-right">$160.00</td>
                      <td className="text-right">
                        <a
                          href="javascript:void(0)"
                          data-loading-text='<i class="fa fa-circle-o-notch fa-spin"></i>'
                          data-record-id={555}
                          className="btn btn-default btn-xs print_report"
                          data-toggle="tooltip"
                          title="Print"
                        >
                          <i className="fa fa-print" />
                        </a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        {/* <MadicineDetailsTab /> */}
      </div>
    </div>
  );
}

export default RadiologyBillDetails;
